"""
core/data/refcoco_loader.py

RefCOCO dataset loader for Spatial-LLaVA training.

What this file does:
    1. Load pkl files generated by stage_1_data_preparation.py (v3 format)
    2. For each sample in __getitem__:
        a. Read the JPEG image from disk (image_path from pkl)
        b. Resize to 384x384 and normalize with ImageNet stats
        c. Tokenize the raw text with LLaVA tokenizer + [LOC] token
        d. Return image tensor + input_ids + bbox tensor
    3. DataLoader workers run __getitem__ in parallel (num_workers > 0)

Why image loading is here (not in stage_1):
    - Stage 1 only saves paths (~3MB pkl vs ~72GB tensor pkl)
    - DataLoader's num_workers handles parallel JPEG loading automatically
    - Much faster overall pipeline

pkl sample format (v3, from stage_1):
    {
        "image_path" : str           absolute path to COCO .jpg
        "text"       : str           raw referring expression
        "bbox"       : Tensor(4,)    normalized [xc, yc, w, h]
    }

DataLoader output per batch:
    {
        "image"     : Tensor(B, 3, 384, 384)  preprocessed images
        "input_ids" : Tensor(B, 77)           tokenized text
        "bbox"      : Tensor(B, 4)            normalized bboxes
    }

Usage:
    from core.data.refcoco_loader import RefCOCODataset

    train_ds = RefCOCODataset.from_config(
        {"data_dir": "data/"}, split="train"
    )
    loader = train_ds.get_dataloader(batch_size=4, num_workers=8)
"""

import os
import pickle
from typing import Dict, Optional

from torch import Tensor
from torch.utils.data import Dataset, DataLoader
from PIL import Image
from torchvision import transforms
from transformers import AutoTokenizer

from core.data.preprocessing import LOC_TOKEN, MAX_LENGTH, IMAGE_SIZE
from core.data.preprocessing import IMAGENET_MEAN, IMAGENET_STD
from core.paths import PATHS


# ── Constants ─────────────────────────────────────────────────────────────────

LLAVA_MODEL_ID = "llava-hf/llava-1.5-7b-hf"
PROMPT_TEMPLATE = "Find the object referred to: {} [LOC]"

# Image transform applied in __getitem__ for each loaded JPEG
IMAGE_TRANSFORM = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
])


# ── Dataset ───────────────────────────────────────────────────────────────────

class RefCOCODataset(Dataset):
    """
    PyTorch Dataset for preprocessed RefCOCO (v3 format).

    What happens at init:
        1. Load pkl file into memory (fast — only paths and strings)
        2. Load LLaVA tokenizer (once, shared across all samples)

    What happens at __getitem__ (called by DataLoader workers):
        1. Get image_path from pkl sample
        2. Open and transform JPEG → Tensor(3, 384, 384)
        3. Tokenize text → Tensor(77,)
        4. Return dict of tensors

    Args:
        pkl_path   : Path to refcoco_{split}.pkl
        split      : "train", "val", or "test" (for logging)
        tokenizer  : Pre-loaded tokenizer (pass to share across splits)
        hf_cache   : Where to cache the tokenizer download
    """

    def __init__(
        self,
        pkl_path: str,
        split: str = "train",
        tokenizer=None,
        hf_cache: str = None,
    ):
        if hf_cache is None:
            hf_cache = str(PATHS.weights)
        self.split = split
        self.pkl_path = os.path.expanduser(pkl_path)
        self.data = self._load_pkl(self.pkl_path)

        if tokenizer is not None:
            self.tokenizer = tokenizer
        else:
            self.tokenizer = self._load_tokenizer(hf_cache)

    # ── Internal loaders ──────────────────────────────────────────

    def _load_pkl(self, path: str) -> list:
        """
        Load the pkl file into a list of sample dicts.

        What this does:
            1. Check the file exists
            2. Deserialize with pickle
            3. Return list of {image_path, text, bbox} dicts

        Raises FileNotFoundError if pkl is missing (run download_data.sh first).
        """
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"pkl not found: {path}\n"
                "Run: bash shared/scripts/download_data.sh"
            )
        print(f"  Loading {self.split} split: {path}")
        with open(path, "rb") as f:
            data = pickle.load(f)
        print(f"  ✓ {len(data):,} samples")
        return data

    def _load_tokenizer(self, hf_cache: str):
        """
        Load LLaVA tokenizer and register the [LOC] special token.

        What this does:
            1. Download tokenizer from HuggingFace (~500MB, cached after first)
            2. Add [LOC] to vocabulary if not already there
            3. Return tokenizer ready for use

        This is called once at dataset init, not per sample.
        """
        os.makedirs(hf_cache, exist_ok=True)
        print(f"  Loading tokenizer: {LLAVA_MODEL_ID} ...")
        tokenizer = AutoTokenizer.from_pretrained(
            LLAVA_MODEL_ID,
            cache_dir=hf_cache,
            use_fast=False,
        )
        if LOC_TOKEN not in tokenizer.get_vocab():
            tokenizer.add_special_tokens(
                {"additional_special_tokens": [LOC_TOKEN]}
            )
        print(f"  ✓ Tokenizer ready (vocab: {len(tokenizer):,})")
        return tokenizer

    # ── Dataset interface ─────────────────────────────────────────

    def __len__(self) -> int:
        """Return total number of samples in this split."""
        return len(self.data)

    def __getitem__(self, idx: int) -> Dict[str, Tensor]:
        """
        Load and return one preprocessed sample.

        What this does (called by DataLoader workers in parallel):
            1. Get sample dict from pkl (image_path, text, bbox)
            2. Open JPEG from disk with PIL
            3. Apply IMAGE_TRANSFORM: resize→384x384, ToTensor, normalize
            4. Format text: "Find the object referred to: {text} [LOC]"
            5. Tokenize text → input_ids Tensor(77,)
            6. Return dict of three tensors

        Args:
            idx : Sample index

        Returns:
            {
                "image"     : Tensor(3, 384, 384)  float32, ImageNet normalized
                "input_ids" : Tensor(77,)          int64, padded/truncated
                "bbox"      : Tensor(4,)           float32, [xc,yc,w,h] in [0,1]
            }
        """
        sample = self.data[idx]

        # ── 1. Load and transform image ────────────────────────────
        pil_img = Image.open(sample["image_path"]).convert("RGB")
        image = IMAGE_TRANSFORM(pil_img)      # Tensor(3, 384, 384)

        # ── 2. Tokenize text ───────────────────────────────────────
        prompt = PROMPT_TEMPLATE.format(sample["text"])
        encoded = self.tokenizer(
            prompt,
            padding="max_length",
            truncation=True,
            max_length=MAX_LENGTH,
            return_tensors="pt",
        )
        input_ids = encoded["input_ids"].squeeze(0).long()   # Tensor(77,)

        # ── 3. Return tensors ──────────────────────────────────────
        return {
            "image": image.float(),
            "input_ids": input_ids,
            "bbox": sample["bbox"].float(),
        }

    # ── DataLoader ────────────────────────────────────────────────

    def get_dataloader(
        self,
        batch_size: int = 4,
        shuffle: bool = True,
        num_workers: int = 8,
        pin_memory: bool = True,
    ) -> DataLoader:
        """
        Build and return a DataLoader for this dataset.

        What this does:
            1. Wrap this dataset in a DataLoader
            2. num_workers processes read JPEGs in parallel
            3. pin_memory speeds up CPU→GPU transfer

        Args:
            batch_size  : Images per batch (default: 4)
            shuffle     : Shuffle each epoch (True for train, False for val/test)
            num_workers : Parallel JPEG loading workers (default: 8)
                          Set to 0 only for debugging.
            pin_memory  : Pin CPU memory for faster GPU transfer (default: True)

        Returns:
            torch.utils.data.DataLoader
        """
        return DataLoader(
            self,
            batch_size=batch_size,
            shuffle=shuffle,
            num_workers=num_workers,
            pin_memory=pin_memory,
            persistent_workers=(num_workers > 0),
        )

    # ── Factory methods ───────────────────────────────────────────

    @classmethod
    def from_config(
        cls,
        config: dict,
        split: str,
        tokenizer=None,
    ) -> "RefCOCODataset":
        """
        Build a RefCOCODataset from a config dict.

        What this does:
            1. Read data_dir from config
            2. Build pkl path: <data_dir>/refcoco_{split}.pkl
            3. Create dataset (tokenizer shared if passed)

        Args:
            config    : Dict with "data_dir" key (and optional "hf_cache")
            split     : "train", "val", or "test"
            tokenizer : Pass train dataset's tokenizer to avoid re-downloading

        Example:
            train_ds = RefCOCODataset.from_config(cfg, "train")
            val_ds   = RefCOCODataset.from_config(
                cfg, "val", tokenizer=train_ds.tokenizer
            )
        """
        data_dir = os.path.expanduser(config["data_dir"])
        pkl_path = os.path.join(data_dir, f"refcoco_{split}.pkl")
        hf_cache = config.get("hf_cache", str(PATHS.weights))
        return cls(
            pkl_path=pkl_path,
            split=split,
            tokenizer=tokenizer,
            hf_cache=hf_cache,
        )


# ── Convenience function ──────────────────────────────────────────────────────

def load_splits(
    data_dir: str = None,
    splits: Optional[list] = None,
    hf_cache: str = None,
) -> Dict[str, RefCOCODataset]:
    """
    Load multiple splits at once, sharing one tokenizer.

    What this does:
        1. Load train split first (downloads tokenizer once)
        2. Reuse same tokenizer for val and test
        3. Return dict of datasets

    Args:
        data_dir : Directory with refcoco_*.pkl files (default: PATHS.data)
        splits   : Which splits to load (default: all three)
        hf_cache : Tokenizer cache directory (default: PATHS.weights)

    Returns:
        {"train": RefCOCODataset, "val": ..., "test": ...}

    Example:
        datasets = load_splits()
        loader = datasets["train"].get_dataloader(batch_size=8)
    """
    if data_dir is None:
        data_dir = str(PATHS.data)
    if hf_cache is None:
        hf_cache = str(PATHS.weights)
    if splits is None:
        splits = ["train", "val", "test"]

    data_dir = os.path.expanduser(data_dir)
    datasets = {}
    tokenizer = None

    for split in splits:
        pkl_path = os.path.join(data_dir, f"refcoco_{split}.pkl")
        ds = RefCOCODataset(
            pkl_path=pkl_path,
            split=split,
            tokenizer=tokenizer,
            hf_cache=hf_cache,
        )
        if tokenizer is None:
            tokenizer = ds.tokenizer   # reuse for remaining splits
        datasets[split] = ds

    return datasets
