"""
core/data/refcoco_loader.py

RefCOCO dataset loader for Spatial-LLaVA training.
"""

import os
import pickle
import torch
from torch.utils.data import Dataset, DataLoader
from torch import Tensor
from typing import Dict, Optional


class RefCOCODataset(Dataset):
    """
    PyTorch Dataset for the pre-processed RefCOCO dataset.
    Loads from pickle files generated by stage_1_data_preparation.py.
    """

    def __init__(self, pkl_path: str, split: str = "train"):
        self.split = split
        self.pkl_path = os.path.expanduser(pkl_path)
        self.data = self._load(self.pkl_path)
        print(
            f"[RefCOCODataset] Loaded {len(self.data)} samples for split='{split}'")

    def _load(self, path: str) -> list:
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"Pickle file not found: {path}\n"
                f"Run pipeline/stage_1_data_preparation.py first."
            )

        with open(path, "rb") as f:
            data = pickle.load(f)

        # Validate structure
        assert isinstance(
            data, list), "Pickle file must contain a list of samples"
        assert len(data) > 0, "Pickle file is empty"

        required_keys = {"image", "input_ids", "bbox"}
        sample_keys = set(data[0].keys())
        missing = required_keys - sample_keys
        assert not missing, f"Samples are missing required keys: {missing}"

        return data

    def __len__(self) -> int:
        return len(self.data)

    def __getitem__(self, idx: int) -> Dict[str, Tensor]:
        sample = self.data[idx]

        image = sample["image"]
        input_ids = sample["input_ids"]
        bbox = sample["bbox"]

        # Ensure correct tensor types
        if not isinstance(image, Tensor):
            image = torch.tensor(image)
        if not isinstance(input_ids, Tensor):
            input_ids = torch.tensor(input_ids)
        if not isinstance(bbox, Tensor):
            bbox = torch.tensor(bbox)

        return {
            "image": image.float(),           # (3, 384, 384) float32
            "input_ids": input_ids.long(),         # (77,)         int64
            "bbox": bbox.float(),             # (4,)          float32
        }

    def get_dataloader(
        self,
        batch_size: int = 4,
        shuffle: bool = True,
        num_workers: int = 2,
        pin_memory: bool = True,
    ) -> DataLoader:
        return DataLoader(
            self,
            batch_size=batch_size,
            shuffle=shuffle,
            num_workers=num_workers,
            pin_memory=pin_memory,
        )

    @classmethod
    def from_config(cls, config: dict, split: str) -> "RefCOCODataset":
        data_dir = os.path.expanduser(config["data_dir"])
        pkl_path = os.path.join(data_dir, f"refcoco_{split}.pkl")
        return cls(pkl_path=pkl_path, split=split)


def load_splits(
    data_dir: str,
    splits: Optional[list] = None,
) -> Dict[str, RefCOCODataset]:
    if splits is None:
        splits = ["train", "val", "test"]

    data_dir = os.path.expanduser(data_dir)
    return {
        split: RefCOCODataset(
            pkl_path=os.path.join(data_dir, f"refcoco_{split}.pkl"),
            split=split,
        )
        for split in splits
    }
