"""
core/data/refcoco_loader.py

RefCOCO dataset loader for Spatial-LLaVA training.

Loads from pkl files generated by stage_1_data_preparation.py (v2 format).
Tokenization is done here at training time — no tokenizer needed in stage_1.

pkl sample format (v2):
    {
        "image" : Tensor(3, 384, 384)  preprocessed image
        "text"  : str                  raw referring expression
        "bbox"  : Tensor(4,)           normalized [xc, yc, w, h]
    }

Usage:
    from core.data.refcoco_loader import RefCOCODataset

    dataset = RefCOCODataset.from_config(
        {"data_dir": "/tmp/data/"},
        split="train"
    )
    loader = dataset.get_dataloader(batch_size=4)
"""

import os
import pickle
from typing import Dict, Optional

# import torch
from torch import Tensor
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer

from core.data.preprocessing import LOC_TOKEN, MAX_LENGTH


# ── Constants ─────────────────────────────────────────────────────────────────

LLAVA_MODEL_ID = "liuhaotian/llava-v1.5-7b"
PROMPT_TEMPLATE = "Find the object referred to: {} [LOC]"


# ── Dataset ───────────────────────────────────────────────────────────────────

class RefCOCODataset(Dataset):
    """
    PyTorch Dataset for preprocessed RefCOCO.

    Loads pkl files (image tensor + raw text + bbox).
    Tokenizes text on-the-fly in __getitem__ using cached tokenizer.

    Args:
        pkl_path   : Path to refcoco_{split}.pkl
        split      : "train", "val", or "test"
        tokenizer  : Pre-loaded LLaVA tokenizer. If None, loaded automatically.
        hf_cache   : HuggingFace cache dir for tokenizer download.
    """

    def __init__(
        self,
        pkl_path: str,
        split: str = "train",
        tokenizer=None,
        hf_cache: str = "/tmp/hf_cache",
    ):
        self.split = split
        self.pkl_path = os.path.expanduser(pkl_path)
        self.data = self._load(self.pkl_path)

        # Load tokenizer (shared across workers via fork)
        if tokenizer is not None:
            self.tokenizer = tokenizer
        else:
            self.tokenizer = self._load_tokenizer(hf_cache)

    # ── Loading ───────────────────────────────────────────────────

    def _load(self, path: str) -> list:
        """Load pkl file and return list of samples."""
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"pkl not found: {path}\n"
                "Run: bash shared/scripts/download_data.sh"
            )
        print(f"  Loading {self.split} split from {path} ...")
        with open(path, "rb") as f:
            data = pickle.load(f)
        print(f"  ✓ {len(data):,} samples loaded")
        return data

    def _load_tokenizer(self, hf_cache: str):
        """Load LLaVA tokenizer and register [LOC] token."""
        os.makedirs(hf_cache, exist_ok=True)
        print(f"  Loading tokenizer from {LLAVA_MODEL_ID} ...")
        tokenizer = AutoTokenizer.from_pretrained(
            LLAVA_MODEL_ID,
            cache_dir=hf_cache,
            use_fast=False,
        )
        if LOC_TOKEN not in tokenizer.get_vocab():
            tokenizer.add_special_tokens(
                {"additional_special_tokens": [LOC_TOKEN]}
            )
        print(f"  ✓ Tokenizer ready (vocab size: {len(tokenizer)})")
        return tokenizer

    # ── Dataset interface ─────────────────────────────────────────

    def __len__(self) -> int:
        return len(self.data)

    def __getitem__(self, idx: int) -> Dict[str, Tensor]:
        """
        Return one sample with tokenized text.

        Returns:
            {
                "image"    : Tensor(3, 384, 384) float32
                "input_ids": Tensor(77,)         int64
                "bbox"     : Tensor(4,)          float32
            }
        """
        sample = self.data[idx]

        image = sample["image"].float()
        bbox = sample["bbox"].float()

        # Tokenize raw text on-the-fly
        text = sample["text"]
        prompt = PROMPT_TEMPLATE.format(text)
        encoded = self.tokenizer(
            prompt,
            padding="max_length",
            truncation=True,
            max_length=MAX_LENGTH,
            return_tensors="pt",
        )
        input_ids = encoded["input_ids"].squeeze(0).long()

        return {
            "image": image,
            "input_ids": input_ids,
            "bbox": bbox,
        }

    # ── DataLoader ────────────────────────────────────────────────

    def get_dataloader(
        self,
        batch_size: int = 4,
        shuffle: bool = True,
        num_workers: int = 0,
        pin_memory: bool = True,
    ) -> DataLoader:
        """
        Return a DataLoader for this dataset.

        Note: num_workers=0 by default because tokenizer is not
        picklable across processes. Use num_workers=0 for safety,
        or pass a pre-loaded tokenizer and set num_workers>0.

        Args:
            batch_size  : Samples per batch
            shuffle     : Shuffle each epoch (True for train)
            num_workers : 0 = main process only (safe with tokenizer)
            pin_memory  : Speed up GPU transfer
        """
        return DataLoader(
            self,
            batch_size=batch_size,
            shuffle=shuffle,
            num_workers=num_workers,
            pin_memory=pin_memory,
        )

    # ── Factory ───────────────────────────────────────────────────

    @classmethod
    def from_config(
        cls,
        config: dict,
        split: str,
        tokenizer=None,
    ) -> "RefCOCODataset":
        """
        Construct dataset from config dict.

        Args:
            config    : Dict with "data_dir" key
            split     : "train", "val", or "test"
            tokenizer : Optional pre-loaded tokenizer (shared across splits)

        Example:
            tok = None  # loaded automatically on first dataset
            train = RefCOCODataset.from_config({"data_dir": "/tmp/data"}, "train")
            val   = RefCOCODataset.from_config(
                {"data_dir": "/tmp/data"}, "val", tokenizer=train.tokenizer
            )
        """
        data_dir = os.path.expanduser(config["data_dir"])
        pkl_path = os.path.join(data_dir, f"refcoco_{split}.pkl")
        hf_cache = config.get("hf_cache", "/tmp/hf_cache")
        return cls(
            pkl_path=pkl_path,
            split=split,
            tokenizer=tokenizer,
            hf_cache=hf_cache,
        )


# ── Convenience ───────────────────────────────────────────────────────────────

def load_splits(
    data_dir: str,
    splits: Optional[list] = None,
    hf_cache: str = "/tmp/hf_cache",
) -> Dict[str, RefCOCODataset]:
    """
    Load multiple splits, sharing one tokenizer instance.

    Args:
        data_dir : Directory containing refcoco_*.pkl files
        splits   : Splits to load (default: ["train", "val", "test"])
        hf_cache : HuggingFace cache dir

    Returns:
        Dict mapping split name → RefCOCODataset
    """
    if splits is None:
        splits = ["train", "val", "test"]

    data_dir = os.path.expanduser(data_dir)
    datasets = {}
    tokenizer = None

    for split in splits:
        pkl_path = os.path.join(data_dir, f"refcoco_{split}.pkl")
        ds = RefCOCODataset(
            pkl_path=pkl_path,
            split=split,
            tokenizer=tokenizer,
            hf_cache=hf_cache,
        )
        # Reuse tokenizer across splits (only download once)
        if tokenizer is None:
            tokenizer = ds.tokenizer
        datasets[split] = ds

    return datasets
